# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20, verbose_name='SN\u5e8f\u53f7')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('purpose', models.CharField(default='\u65e0', max_length=80, verbose_name='\u4f7f\u7528\u76ee\u7684')),
                ('person', models.CharField(default='\u65e0', max_length=20, verbose_name='\u8d1f\u8d23\u4eba')),
                ('always', models.BooleanField(verbose_name='\u957f\u671f\u5360\u7528')),
                ('left_time', models.IntegerField(default='0', verbose_name='\u5269\u4f59\u5929\u6570')),
                ('update_time', models.DateField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('area', models.CharField(max_length=20, verbose_name='\u533a\u57df')),
                ('cabinet', models.CharField(max_length=20, verbose_name='\u673a\u67dc')),
                ('bmc_ip', models.GenericIPAddressField(verbose_name='BMC IP')),
                ('mgr_ip', models.GenericIPAddressField(verbose_name='\u7ba1\u7406 IP')),
                ('cpu', models.CharField(max_length=20, verbose_name='CPU')),
                ('RAM', models.CharField(max_length=20, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(max_length=20, verbose_name='\u5b58\u50a8')),
                ('mac_0', models.CharField(max_length=20, verbose_name='\u7f51\u53611 MAC \u5730\u5740')),
                ('mac_1', models.CharField(max_length=20, verbose_name='\u7f51\u53612 MAC \u5730\u5740')),
                ('mac_2', models.CharField(max_length=20, verbose_name='\u7f51\u53613 MAC \u5730\u5740')),
                ('mac_3', models.CharField(max_length=20, verbose_name='\u7f51\u53614 MAC \u5730\u5740')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668',
            },
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP \u5730\u5740')),
                ('person', models.CharField(max_length=20, verbose_name='\u8d1f\u8d23\u4eba')),
                ('purpose', models.CharField(default='\u65e0', max_length=20, verbose_name='\u4f7f\u7528\u76ee\u7684')),
                ('always', models.BooleanField(verbose_name='\u957f\u671f\u5360\u7528')),
                ('left_time', models.IntegerField(verbose_name='\u5269\u4f59\u5929\u6570')),
                ('update_time', models.DateField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('bmc_ip', models.BooleanField(verbose_name='\u662f\u5426BMC')),
            ],
            options={
                'verbose_name': 'ip',
                'verbose_name_plural': 'ip',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='\u4e3b\u673a\u540d')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fibermotor.Region', verbose_name='\u673a\u623f'),
        ),
    ]
