# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='\u59d3\u540d')),
                ('mail', models.EmailField(max_length=80, verbose_name='\u90ae\u7bb1')),
                ('phone', models.BigIntegerField(verbose_name='\u7535\u8bdd')),
                ('update_time', models.DateField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
